
export const COMPANIESDATAFETCH = "COMPANIESDATAFETCH";
export const COMPANIESDATASUCCESS = "COMPANIESDATASUCCESS";
export const COMPANIESDATAFAILURE = "COMPANIESDATAFAILURE";

export const COMPANIESADDDATAFETCH = "COMPANIESADDDATAFETCH";
export const COMPANIESADDDATASUCCESS = "COMPANIESADDDATASUCCESS";
export const COMPANIESADDDATAFAILURE = "COMPANIESADDDATAFAILURE";